-- Copie le catalogue historique dans la table administrable.
-- Cette migration n'ecrit pas dans ordres_travail : les plans existants restent inchanges.
insert into public.plan_action_problem_options (lot, famille, mode_defaillance, actif)
values
  ('CVC', 'CVC', 'Inexistant', true),
  ('CVC', 'CVC', 'Insuffisant', true),
  ('CVC', 'CVC', 'Trop froid', true),
  ('CVC', 'CVC', 'Odeur', true),
  ('CVC', 'CVC', 'Bruyant', true),
  ('CVC', 'CVC', 'Fuite de gaz', true),
  ('CVC', 'CVC', 'Fuite de condensat', true),
  ('CVC', 'CVC', 'Manque de gaz', true),
  ('CVC', 'CVC', 'Alarme / Defaut', true),
  ('CVC', 'CVC', 'Probleme d''hygrometrie', true),
  ('CVC', 'CVC', 'Demande de mise en service', true),
  ('CVC', 'CVC', 'Demande de mise a l''arret', true),
  ('CVC', 'CVC', 'Autre', true),
  ('CVC', 'Extraction', 'Inexistante', true),
  ('CVC', 'Extraction', 'Odeur', true),
  ('CVC', 'Extraction', 'Bruyante', true),
  ('CVC', 'Extraction', 'Alarme / Defaut', true),
  ('CVC', 'Extraction', 'Autre', true),
  ('Electricite', 'Electricite', 'Absence / Coupure', true),
  ('Electricite', 'Electricite', 'Baisse de tension', true),
  ('Electricite', 'Electricite', 'protection / isolation / reparation des cables', true),
  ('Electricite', 'Electricite', 'Alarme / defaut', true),
  ('Electricite', 'Electricite', 'Plus de courant sur un appareil', true),
  ('Electricite', 'Electricite', 'prise hors service', true),
  ('Electricite', 'Electricite', 'Defaut onduleur', true),
  ('Electricite', 'Electricite', 'Autre', true),
  ('Eclairage', 'Eclairage', 'Probleme eclairage', true),
  ('Eclairage', 'Eclairage', 'problemes eclairage piscine', true),
  ('Eclairage', 'Eclairage', 'Pose ou reparation eclairage', true),
  ('Eclairage', 'Eclairage', 'Disjonction batiment', true),
  ('Eclairage', 'Eclairage', 'Plus de lumiere dans le bureau / a l''etage', true),
  ('Eclairage', 'Eclairage', 'Spot au sol', true),
  ('Eclairage', 'Eclairage', 'Luminaire plafond hors service', true),
  ('Eclairage', 'Eclairage', 'Interrupteur hors service', true),
  ('Eclairage', 'Eclairage', 'Reparation lampe individuelle de bureau', true),
  ('Eclairage', 'Eclairage', 'Pb alimentation Enseigne/totem', true),
  ('Eclairage', 'Eclairage', 'Eclairage Enseigne', true),
  ('Eclairage', 'Eclairage', 'Autre', true),
  ('Plomberie', 'Plomberie', 'Engorgement', true),
  ('Plomberie', 'Plomberie', 'Fuite', true),
  ('Plomberie', 'Plomberie', 'Rupture / casse', true),
  ('Plomberie', 'Plomberie', 'Pompe de relevage / EU / Puits', true),
  ('Plomberie', 'Plomberie', 'Probleme de pression', true),
  ('Plomberie', 'Plomberie', 'Probleme qualite eau', true),
  ('Plomberie', 'Plomberie', 'Coupure Eau', true),
  ('Plomberie', 'Plomberie', 'Lavabo / Douchettes', true),
  ('Plomberie', 'Plomberie', 'PB siphon', true),
  ('Plomberie', 'Plomberie', 'regard / WC bouche', true),
  ('Plomberie', 'Plomberie', 'fuite robinet Lavabo', true),
  ('Plomberie', 'Plomberie', 'Urinoir fuite poussoir', true),
  ('Plomberie', 'Plomberie', 'WC fuite', true),
  ('Plomberie', 'Plomberie', 'WC Mecanisme chasse d''eau', true),
  ('Plomberie', 'Plomberie', 'Inondation', true),
  ('Plomberie', 'Plomberie', 'Deratisation et traitement des locaux', true),
  ('Plomberie', 'Plomberie', 'Fontaine d''eau glacee', true),
  ('Ascenseur', 'Ascenseur', 'Pb alimentation electrique', true),
  ('Ascenseur', 'Ascenseur', 'Pb securite des portes', true),
  ('Ascenseur', 'Ascenseur', 'Pb eclairage inr', true),
  ('Ascenseur', 'Ascenseur', 'coulisse', true),
  ('Courant faible', 'internet/intranet/tel/fax', 'Pb interne de connexion', true),
  ('Courant faible', 'internet/intranet/tel/fax', 'Nouvelle installation', true),
  ('Incendie', 'Securite Incendie', 'Pb. Detection et Incendie', true),
  ('Incendie', 'Securite Incendie', 'Pb.Extincteurs', true),
  ('Incendie', 'Securite Incendie', 'Pb. Controle d''acces', true),
  ('Incendie', 'Securite Incendie', 'Pb.Video / Camera / Magnetoscope', true),
  ('Incendie', 'Securite Incendie', 'Alarme', true),
  ('Incendie', 'Securite Incendie', 'Installation d''extincteurs', true),
  ('Incendie', 'Securite Incendie', 'Expiration extincteur', true),
  ('Incendie', 'Securite Incendie', 'Pb. Eclairage secours', true),
  ('Incendie', 'Securite Incendie', 'Autre', true),
  ('Menuiserie', 'Menuiserie', 'Pb. Serrurerie', true),
  ('Menuiserie', 'Menuiserie', 'Pb. Menuiserie', true),
  ('Menuiserie', 'Menuiserie', 'Fourniture cle de bureau', true),
  ('Menuiserie', 'Menuiserie', 'Serrure / Verrou HS', true),
  ('Menuiserie', 'Menuiserie', 'Pb SAS', true),
  ('Menuiserie', 'Menuiserie', 'Poignee de porte HS', true),
  ('Menuiserie', 'Menuiserie', 'Poignee de fenetre HS', true),
  ('Menuiserie', 'Menuiserie', 'Menuiserie', true),
  ('Menuiserie', 'Menuiserie', 'Pb Fermeture Porte / Fenetre', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pb. Vitrerie', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'problemes lit medical', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pb. Revetement Sol', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pb. Revetement Mur', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pb. Revetement Plafond', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pb. Toiture', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Gros oeuvre', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pb.de store/rideau', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Barre antipatique HS', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Faux-plafond / Faux-plancher', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Fermeture fenetre bureau', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Fixation barre de seuil', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pose depose boite a cle', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pose depose de tableau mural', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pose ou depose store', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Deplacement cloison', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pose ou reparation moquette ou carrelage', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pose protection cable au sol', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Infiltration (plafond / mur)', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Pb.seche main', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Autre', true),
  ('Secondes Oeuvres', 'Secondes_Oeuvres', 'Revetement mural (papier / peinture / carrelage)', true),
  ('Divers Services', 'Divers Services', 'A preciser', true)
on conflict (lot, famille, mode_defaillance)
  where mode_defaillance is not null
  do nothing;

notify pgrst, 'reload schema';

